FROM golang:1.22

# Set the working directory to /app
WORKDIR /test

# Copy the current directory contents into the container at /app
COPY ./test/bench /test

# Run the tests
CMD ["go", "test", ".", "-bench", ".", "-benchmem", "-count=10"]